# Generated by Django 4.2.20 on 2025-04-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='region',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='location',
            name='venue',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
